kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-single-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G